export { default as Nav } from './components/Nav.svelte';
export { default as Footer } from './components/Footer.svelte';
export { default as Hero } from './components/Hero.svelte';
export { default as HowItWorks } from './components/HowItWorks.svelte';
export { default as StartupCard } from './components/StartupCard.svelte';
export { default as StartupGrid } from './components/StartupGrid.svelte';
export { default as CloneCard } from './components/CloneCard.svelte';
export { default as StartupDetail } from './components/StartupDetail.svelte';
export { default as PurchaseModal } from './components/PurchaseModal.svelte';
